name: MIAH Music
favicon: null
layout_spectrum: 0.27434142981655896
typography_spectrum: 0.48787988699041307
title: MIAHmusic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5e552a'
    - '#9f904b'
    - '#e5ddb8'
  brandStrength: 0.3582867674995214
  lightness: 0.857120860600844
  saturation: 0.9126523227896541
  rhythmicContrast: 0.19688823097385466
purpose: []
